version: 0.0
os: linux
files:
  - source: requirements.txt
    destination: /home/ec2-user/landmark
  - source: application.py
    destination: /home/ec2-user/landmark
  - source: /src
    destination: /home/ec2-user/landmark
  - source: /conf
    destination: /home/ec2-user/landmark
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
